### ISSUE TITLE
BDSLM莫名完全无法使用

### ISSUE THREAD

**Issue by MengYang8481** [LiteLDev/BDSLM#10]
BDS 1.18.32 ，LL 2.2.3 ，插件版本：
![image](https://user-images.githubusercontent.com/23436744/168949320-a3e27527-90d4-46e7-8e48-32b37320a3d3.png)
表现为
![image](https://user-images.githubusercontent.com/23436744/168949406-d643441a-378a-42c9-9b73-1e2327cc498c.png)
head title正常显示，但是没有地图，已确保生成
![image](https://user-images.githubusercontent.com/23436744/168949541-9c075ca3-3868-4f27-91a2-8ae3a34d1984.png)
已大概率排除nginx原因；

**Comment by gtr3qq** [comment]
你的网络可能有问题，bdslm需要从网络获取openlayers CSS ,JS。你诊断出现的错误如果我没猜错前两个就是timeout。我也遇到过，挂梯子解决……。
你考虑使用梯子？当然，如果bdslm可以集成下的话……well。

**Comment by MengYang8481** [comment]
> 你的网络可能有问题，bdslm需要从网络获取openlayers CSS ,JS。你诊断出现的错误如果我没猜错前两个就是timeout。我也遇到过，挂梯子解决……。 你考虑使用梯子？当然，如果bdslm可以集成下的话……well。

It may not be the problem you mentioned. There will still be an error when the localhost:5000 test cannot load the map. I infer that the plugin is abnormal, but I am not sure... The web page is blank, including zoom in and zoom out, and the coordinates are displayed.
Also VPNs are against the law in China, this is a good idea but not possible...

**Comment by gtr3qq** [comment]
> 

not so much, there are still vpns commercially operates in china but under a different name _accelerators_.
and agin, you did not understand my words. it is noting to do with local loopback or not, it is to do with the fact BDSLM needs those two libraries from the net to work. One could argue it is the author's fault to not to en-cooperate those two libs given the  current state of networking in china. but i think it is you broadband provider's fault to not give you full access of the net. Anyway, it would be much more helpful if you can give more diagnose infos to see whats what.

**Comment by pa733** [comment]
jquery和jsdelivr目前已恢复正常。
感谢您的反馈，在我找到更好的替代品后我会立即更换。

**Comment by pa733** [comment]
已替换为staticfile.org
