### ISSUE TITLE
BDSLM无法在1.18.31使用

### ISSUE THREAD

**Issue by SOURsLEMONS** [LiteLDev/BDSLM#11]
无法在版本1.18.31使用，启动无法渲染
仅安装了LL加载器，重新生成地图。依然无法加载
![Screenshot_2022-05-19-09-54-25-00_86e04deac6f255e7d8c10bb85df03856](https://user-images.githubusercontent.com/89817084/169192262-d4e9936a-bc5f-4aa0-b22f-fd2da0157cc4.jpg)

**Comment by SOURsLEMONS** [comment]
ll版本2.2.2.地图插件版本好像是0.3
配置文件全部都是新的，没有改

**Comment by MengYang8481** [comment]
#10 跟帖而不是重复打开新的issue

**Comment by SOURsLEMONS** [comment]
> #10跟帖是重复打开新的问题

qwq第一次用，感觉跟那个问题不太一样，所以就开新问题了

**Comment by pa733** [comment]
貌似是地图无任何内容导致的生成失败，
请尝试进入服务器生成区块后重启服务端。
等待您的回复

**Comment by MengYang8481** [comment]
> 貌似是地图无任何内容导致的生成失败， 请尝试进入服务器生成区块后重启服务端。 等待您的回复

像是找不到 .ldb ...我的也是类似，明明在上一个版本可以正常使用...详见LL 2群

**Comment by pa733** [comment]
> > 貌似是地图无任何内容导致的生成失败， 请尝试进入服务器生成区块后重启服务端。 等待您的回复
> 
> 
> 
> 像是找不到 .ldb ...我的也是类似，明明在上一个版本可以正常使用...详见LL 2群

与一般的问题不一样，这可以从报错内容中，区块数量为0看出来
