### ISSUE TITLE
地图生成失败

### ISSUE THREAD

**Issue by ermosama** [LiteLDev/BDSLM#14]
出现报错
![QQ截图20220604033843](https://user-images.githubusercontent.com/47210274/172023184-53049c05-6e0e-45e2-9bac-1e1e730b1639.png)
重装插件与重新配置服务器环境也会复现

**Comment by ermosama** [comment]
bds版本 1.18.33.02 ll版本2.2.5 BDSLM版本最新一次构建

**Comment by MengYang8481** [comment]
#11 不要重复开新

**Comment by pa733** [comment]
与#11重复
duplicated to #11

**Comment by pa733** [comment]
已加入至To-Do列表

**Comment by pa733** [comment]
与 #9 重复
duplicated to #9
