### ISSUE TITLE
BDSLM崩服

### ISSUE THREAD

**Issue by TacKana** [LiteLDev/BDSLM#20]
20:04:13 INFO [扫地小奏] 清理僵尸成功
20:04:49 INFO [Chat] <Babaqs> e
[Crashed!]
-- Unhandled Exception in -> BDSLM.dll
-- Exception Code: 0xC0000005
-- Minidump generated in Directory ./logs/Crash
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFDAC1D5400  [BDSLM.dll]
[StackTrace] Function o__realloc_base at 0x7FFDBA26FB20  [ucrtbase.dll<6.2.14393.3659>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFDBCF184C0  [KERNEL32.DLL<6.2.14393.4651>]
[StackTrace] Function RtlUserThreadStart at 0x7FFDBDDD1770  [ntdll.dll<6.2.14393.4886>]
20:04:57 INFO [Nillauncher] BDS进程退出，当前非正常启动次数：1
20:04:57 INFO [Nillauncher] 进程非正常退出，即将重启

**Comment by pa733** [comment]
请列出BDS与LL版本，并描述错误在什么时候发生。
此问题能否稳定复现？

**Comment by pa733** [comment]
已确认问题存在，正在排查

**Comment by pa733** [comment]
无法复现并且无法获得关于此问题的详细信息

**Comment by pa733** [comment]
此问题仍存在

**Comment by PA733** [comment]
感谢您的反馈，我们正在采取行动解决这个问题。目前我们已经默认禁用了webchat服务，以缓解此问题。

**Comment by youpuhe** [comment]
已尝试修复，等待后续反馈。

**Comment by PA733** [comment]
已尝试修复，等待后续反馈。
