### ISSUE TITLE
为什么minebbs上显示以失效，难道准备放弃这个项目了吗？

### ISSUE THREAD

**Issue by DDS-ALL** [LiteLDev/BDSLM#21]

**Comment by pa733** [comment]
[https://www.minebbs.com/threads/mb.13062/](https://www.minebbs.com/threads/mb.13062/)
项目还会继续更新

**Comment by pa733** [comment]
另外，请不要提交无用issue，这会污染issue区。
以后遇到类似问题请私聊。
