### ISSUE TITLE
BDSLM导致物理机崩溃

### ISSUE THREAD

**Issue by DZDGame** [LiteLDev/BDSLM#22]
系统：windowes server 2022

BDS：1.19.10

LL：2.4.2

在生成地图时会导致物理机崩溃

![image](https://user-images.githubusercontent.com/103090256/180607003-9ae82345-441a-4f0f-8fc9-9370596899dc.png)

**Comment by pa733** [comment]
https://lmstfy.net/bing/?q=55So5oi35oCB56iL5bqP5Lya5a+86Ie0d2luZG93c+iTneWxj+WQlw==
