### ISSUE TITLE
修改样式问题

### ISSUE THREAD

**Issue by 272416939** [LiteLDev/BDSLM#24]
修改好样式后，一旦重启服务器就会恢复原样，是我食用方法不对吗还是不支持修改？
![IMG_20220806_155629](https://user-images.githubusercontent.com/27958553/183240173-6067bb51-fc41-4234-bc4c-73e05955dfec.jpg)

**Comment by dragonjie233** [comment]
要把修改好的前端文件放进 `/unmined/templates` 目录里面的 default.web.template.zip 压缩包

**Comment by 272416939** [comment]
> 要把修改好的前端文件放进 目录里面的 default.web.template.zip 压缩包`/unmined/templates`

好的👍
