### ISSUE TITLE
服务器崩溃

### ISSUE THREAD

**Issue by 272416939** [LiteLDev/BDSLM#25]
BDSLM使用最新构建版本（41）
BDS版本：1.19.10.03
LL：2.4.2
日志：https://owoser.lanzouy.com/ii34A094b8pi
原因未知

**Comment by pa733** [comment]
收到，正在排查

**Comment by pa733** [comment]
非常感谢，由于此issue与 #20 重复，我们将将此issue关闭。
您提交的日志文件很有用，这将极大地帮助我们排错。
