### ISSUE TITLE
建议挂起后把地图复制出来

### ISSUE THREAD

**Issue by cngege** [LiteLDev/BDSLM#26]
RT
开始的时候建议挂起后把地图复制出来后恢复挂起，然后用复制出来的存档生成网页地图

否则挂起的时间过长，可能导致其他存档备份插件出现问题（我的服务器运行BDSLM，会长时间挂起，症状是关闭服务器的时候关闭不了）

**Comment by pa733** [comment]
不现实，这么做会大量占用硬盘资源。
另外关服卡住问题是BDSLM的逻辑错误，正在处理

**Comment by cngege** [comment]
不会啊 ，怎么会占用大量硬盘资源呢，挂起后将整个存档复制出来，然后后面的生成网页地图就和BDS没什么关系了
也可以在开服之前 （插件加载的时候服务器还没开启），把存档复制出来（就不用挂起了）然后生成网页地图

**Comment by pa733** [comment]
我指的是占用硬盘容量
此外复制时会对硬盘性能造成影响

**Comment by cngege** [comment]
那好吧

**Comment by pa733** [comment]
我可能没有描述清楚我的想法。
是这样的，我个人认为能把BDSLM对服务器性能的影响缩减得越小越好。
所以对于关服卡住问题，目前的方案是参考yq的BackuHelper阻止用户关服。后续会考虑让BDSLM捕获stop命令并在恢复地图后继续关服进程。
对于挂起地图会阻止备份插件备份地图的问题，目前的设想是在ll内添加对挂起地图的api，实现锁机制（实现后可以让备份插件与渲染进程互不冲突，可以同时进行）。
非常感谢您的反馈，但目前我空余时间不多，相关设想可能实现起来要很久。
如果大佬有兴趣的话可以一起来做做呀，直接往pr扔就行。
