### ISSUE TITLE
BDSLM地图生成失败

### ISSUE THREAD

**Issue by engsr6982** [LiteLDev/BDSLM#29]
服务器系统
windows server 2012r2
游戏版本：1.19.20
Liteloder版本：2.5.1
BDSLM版本，8月15日最新构建
![D6E12271-18CD-43B2-BB80-11D209685B36](https://user-images.githubusercontent.com/109733049/185724643-7db3e883-ad98-465e-a77f-3cd0105da792.jpeg)

**Comment by pa733** [comment]
感谢反馈，但本issue与 #28 重复。
本错误是由于地图内没有任何数据导致的，建议进入服务器生成区块后重启服务器来生成地图文件
