### ISSUE TITLE
网页无法正常加载显示

### ISSUE THREAD

**Issue by bbsupn** [LiteLDev/BDSLM#30]
从刚启动服务端完成·提示了一次正在挂起地图，等待挂起后渲染。一直处于挂起中状态，地图不渲染，后续也没有任何提示，尝试重新安装插件很多次，也依然没有效果，希望加入手动强制开始渲染功能，不知道为什么这个挂起一直在等待，目前卫星地图处于用不了的状态
*
06:19:20 INFO [BDSLM] 正在挂起地图，将在挂起后启动渲染
*
接着就没有下文了

**Comment by pa733** [comment]
请查看任务管理器以判断unmined-cli的运行状态

**Comment by bbsupn** [comment]
检查了一下发现没有这个进程，如何解决？

**Comment by bbsupn** [comment]
启动服务器卫星地图插件正常加载了，但这个unmined-cli进程并不会被创建，这个要怎么解决

**Comment by pa733** [comment]
请尝试在bds根目录执行`.\plugins\BDSLM\unmined\unmined-cli.exe web render --world="./worlds/你地图的名字" --output="./plugins/BDSLM/unmined-web/" --imageformat=webp -c`，然后观察有无报错。

**Comment by bbsupn** [comment]
问题已解决，感谢

**Comment by bbsupn** [comment]
地图已完成渲染，但网页上不能正常显示，我F12网页控制台看了下有报错
![QQ截图20220828224453](https://user-images.githubusercontent.com/85688636/187080000-0fc227ff-16c1-4fa7-84e4-82dfae9c0c86.png)
![QQ截图20220828224422](https://user-images.githubusercontent.com/85688636/187080090-f7cabc4b-5374-4945-9bad-2cbcf97d42da.png)

**Comment by pa733** [comment]
无法复现
