### ISSUE TITLE
玩家位置没有在网站显示

### ISSUE THREAD

**Issue by 1772189738** [LiteLDev/BDSLM#36]
报错：![image](https://user-images.githubusercontent.com/62361806/205640185-f1e25416-a24f-4bf6-a28c-d28c3d0cdd35.png)
网站上只有地图没有显示玩家实时位置

**Comment by pa733** [comment]
感谢反馈，已确认存在此问题，正在处理中

**Comment by pa733** [comment]
已在 [c04bad1](https://github.com/LiteLDev/BDSLM/commit/c04bad1d18ce0762b8fbfdf5595c5f653b8995d1) 中修复。
