### ISSUE TITLE
新版本方块和屏障，光源方块等出现紫色

### ISSUE THREAD

**Issue by 1772189738** [LiteLDev/BDSLM#38]
![image](https://user-images.githubusercontent.com/62361806/207222025-25cf76dd-a583-4ebb-bb63-646c028dcce6.png)
新版本方块和屏障，光源方块等出现紫色，希望更新

**Comment by pa733** [comment]
Duplicated to #5

**Comment by pa733** [comment]
感谢反馈，但此issue与 #5 重复，建议您跟帖而不是开新。

**Comment by 1772189738** [comment]
> 感谢反馈，但此issue与 #5 重复，建议您跟帖而不是开新。

抱歉，不太会用github

**Comment by 1772189738** [comment]
> 感谢反馈，但此issue与 #5 重复，建议您跟帖而不是开新。

是否接定制插件？加个qq吧
