### ISSUE TITLE
不定时会崩溃服务器

### ISSUE THREAD

**Issue by sunnyday666** [LiteLDev/BDSLM#39]
[Crashed!]
-- Unhandled Exception in -> BDSLM.dll
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7EBB4D6  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7EBA3C2  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7EBA794  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7EB9DC6  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7EB90A5  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7EB5C6E  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7EB7DDF  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7EC1C52  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7EB8599  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7EAB7AC  [BDSLM.dll]
[StackTrace] Function onPostInit at 0x7FFAA7EAA350  [BDSLM.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAA7ECA41E  [BDSLM.dll]
[StackTrace] Function configthreadlocale at 0x7FFAC27D1B20  [ucrtbase.dll<6.2.19041.789>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAC27D1BB2  [ucrtbase.dll<6.2.19041.789>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFAC3EB7600  [KERNEL32.DLL<6.2.19041.2364>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAC3EB7614  [KERNEL32.DLL<6.2.19041.2364>]
[StackTrace] Function RtlUserThreadStart at 0x7FFAC4EA2680  [ntdll.dll<6.2.19041.2130>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FFAC4EA26A1  [ntdll.dll<6.2.19041.2130>]

这是崩溃日志，看后台是突然崩溃的，没有前兆。

**Comment by pa733** [comment]
dmp有吗？
之前也遇到过类似的问题。
另外你的这个issue可能是重复的

**Comment by sunnyday666** [comment]
> dmp有吗？ 之前也遇到过类似的问题。 另外你的这个issue可能是重复的。 不过还是感谢反馈。
[CrashDump_20221228_13-12-51.dmp.txt](https://github.com/LiteLDev/BDSLM/files/10351463/CrashDump_20221228_13-12-51.dmp.txt)
把txt删掉就好了，我这还有好多dmp文件，还需要更多的吗

**Comment by pa733** [comment]
暂时不需要了，非常感谢您提供的信息

**Comment by pa733** [comment]
与 #20 重复
duplicated to #20
