### ISSUE TITLE
README.md 中的链接失效

### ISSUE THREAD

**Issue by TukangM** [LiteLDev/BDSLM#44]
`https://jenkins.bllxl.com/job/LiteLDev/job/BDSLM/job/main/`
![image](https://github.com/LiteLDev/BDSLM/assets/91467886/15917208-5cb7-4b0b-b589-b7219409cd9d)

**Comment by PA733** [comment]
请详细说明您遇到的问题。
比如您是从哪获得此链接的？

**Comment by TukangM** [comment]
From readme.md
How to use Download the zip file from bllxl jenkins, then unzip the corresponding zip file. Note: The BDSLM.dll file should be in the same directory as the preload.conf file.



> How to use
> Download the zip file from bllxl jenkins, then unzip the corresponding zip file. Note: The BDSLM.dll file should be in the same directory as the preload.conf file.

**Comment by PA733** [comment]
感谢回复。确实是我疏忽了。
您可以在 [这里]https://jenkins.bllxl.com/job/BDSLM/job/main/) 下载到BDSLM。
我们已定位此问题，并将尽快修复。

**Comment by TukangM** [comment]
ok.

**Comment by PA733** [comment]
已在 [a1e2d33](https://github.com/LiteLDev/BDSLM/commit/a1e2d333a86278b3f0264745f02898f74e4b8045) 中修复。
