### ISSUE TITLE
1.20疯狂报错

### ISSUE THREAD

**Issue by DanielToyama** [LiteLDev/BDSLM#45]
21:28:21 ERROR [LiteLoader] SEH exception occurred in ScheduleTask!
21:28:21 ERROR [LiteLoader] SEH_UNKNOW_ERROR
21:28:21 ERROR [LiteLoader] TaskId: 1
21:28:21 ERROR [LiteLoader] In Plugin: <BDSLM 0.3.4>
21:28:22 ERROR [LiteLoader] SEH exception occurred in ScheduleTask!
21:28:22 ERROR [LiteLoader] SEH_UNKNOW_ERROR
21:28:22 ERROR [LiteLoader] TaskId: 1
21:28:22 ERROR [LiteLoader] In Plugin: <BDSLM 0.3.4>
21:28:23 ERROR [LiteLoader] SEH exception occurred in ScheduleTask!
21:28:23 ERROR [LiteLoader] SEH_UNKNOW_ERROR
21:28:23 ERROR [LiteLoader] TaskId: 1
21:28:23 ERROR [LiteLoader] In Plugin: <BDSLM 0.3.4>
21:28:24 ERROR [LiteLoader] SEH exception occurred in ScheduleTask!
21:28:24 ERROR [LiteLoader] SEH_UNKNOW_ERROR
21:28:24 ERROR [LiteLoader] TaskId: 1
21:28:24 ERROR [LiteLoader] In Plugin: <BDSLM 0.3.4>
21:28:25 ERROR [LiteLoader] SEH exception occurred in ScheduleTask!
21:28:25 ERROR [LiteLoader] SEH_UNKNOW_ERROR
21:28:25 ERROR [LiteLoader] TaskId: 1
21:28:25 ERROR [LiteLoader] In Plugin: <BDSLM 0.3.4>
21:28:26 ERROR [LiteLoader] SEH exception occurred in ScheduleTask!
21:28:26 ERROR [LiteLoader] SEH_UNKNOW_ERROR
21:28:26 ERROR [LiteLoader] TaskId: 1
21:28:26 ERROR [LiteLoader] In Plugin: <BDSLM 0.3.4>
21:28:27 ERROR [LiteLoader] SEH exception occurred in ScheduleTask!
21:28:27 ERROR [LiteLoader] SEH_UNKNOW_ERROR
21:28:27 ERROR [LiteLoader] TaskId: 1
21:28:27 ERROR [LiteLoader] In Plugin: <BDSLM 0.3.4>
就这样一秒4条，并且无法显示玩家位置。（可以正常渲染地图

**Comment by PA733** [comment]
@DanielToyama 尝试关闭聊天转发以缓解此问题

**Comment by DanielToyama** [comment]
> @DanielToyama 尝试关闭聊天转发以缓解此问题

如何关闭？配置文件如下
webChat:
  enabled: false
  outbound:
    prefix: "<span style=\"color: cyan;\">[SERVER]</span>"
mapRender:
  zoomIn: -2
  zoomOut: 4

已经是false状态

**Comment by PA733** [comment]
@DanielToyama 可能问题出在别的地方。
请问您遇到的错误频繁吗？
是否每次重启服务器都会遇到？

**Comment by DanielToyama** [comment]
> @DanielToyama 可能问题出在别的地方。 请问您遇到的错误频繁吗？ 是否每次重启服务器都会遇到？

非常频繁。根据观察，服务器存在玩家就会出现，不存在玩家就不会产生，并且此报错持续刷屏直到玩家登出。升级1.20最新版后产生，并且地图无法产生玩家位置

**Comment by PA733** [comment]
@DanielToyama 您使用的LiteLoaderBDS版本号为多少？

**Comment by DanielToyama** [comment]
Bedrock-1.20.0.01-LL-Beta....忘记更新了，回头试试

**Comment by DanielToyama** [comment]
> @DanielToyama 您使用的LiteLoaderBDS版本号为多少？

已测试，最新发布的2.14.1release依然存在此问题

**Comment by PA733** [comment]
@DanielToyama 感谢您的耐心反馈，我们将尽快修复此问题。
建议您在我们修复此问题前，暂时卸载本插件。

**Comment by PA733** [comment]
已在 [425ac54](https://github.com/LiteLDev/BDSLM/commit/425ac5430dd755743e1899f33fd3e6a980428ada) 中修复

**Comment by DanielToyama** [comment]
感谢大佬
