### ISSUE TITLE
草地在海洋生物群系里渲染出来是棕色的

### ISSUE THREAD

**Issue by HongyiMC** [LiteLDev/BDSLM#5]
目前还有其他渲染错误，可以手动修改吗

**Comment by pa733** [comment]
这不是BDSLM的问题，可能是unmined的问题。
您可在BDSLM/unmined/config中修改。

**Comment by PA733** [comment]
请尝试与unmined作者联系，我们暂时无法修复此问题。

**Comment by PA733** [comment]
在更新了unmined版本后，部分方块的渲染已得到修正。
建议您尝试新版BDSLM。
