### ISSUE TITLE
关于一个地图长时间运行或被BDS修复就会无法使用BDSLM

### ISSUE THREAD

**Issue by MengYang8481** [LiteLDev/BDSLM#9]
BDS 1.18.32 LL 2.2.3 BDSLM最新版
表现为无法读取某个ldb文件，
![image](https://user-images.githubusercontent.com/23436744/168276899-3482f2e5-7831-4464-a39d-18f1f2b3ca01.png)
我也不知道什么情况会丢失，似乎基本上存档一大都会丢文件，，
我的建议吧，遇到这种直接跳过读取...
不知道能不能做到QAQ

**Comment by MengYang8481** [comment]
又有一个地图用不了BDSLM插件...表现如上
当一个地图运行时间很久就会出现这种情况，建议是遇到找不到的.ldb直接跳过....不知道能不能做到
我的两个地图分别开了7个月和5个月，均为同样的状况

**Comment by pa733** [comment]
已确认修复
请尝试新的构建

**Comment by MengYang8481** [comment]
![42@9(9GJT9M7_%F`U WSCZM](https://user-images.githubusercontent.com/23436744/178498854-818dbef4-37e8-4340-af95-506e603a3a65.jpg)
